{ "run_type",       "sp",               parse_run_type,  NULL,           offsetof(struct config, run_type)           },
{ "coord",          "xyzabc",           parse_coord,     NULL,           offsetof(struct config, coord_type)         },
{ "units",          "angs",             parse_units,     NULL,           offsetof(struct config, units_factor)       },
{ "terms",          "elec pol disp xr", parse_terms,     NULL,           offsetof(struct config, terms)              },
{ "elec_damp",      "screen",           parse_elec_damp, NULL,           offsetof(struct config, elec_damp)          },
{ "disp_damp",      "tt",               parse_disp_damp, NULL,           offsetof(struct config, disp_damp)          },
{ "pol_damp",       "tt",               parse_pol_damp,  NULL,           offsetof(struct config, pol_damp)           },
{ "enable_pbc",     "false",            parse_bool,      NULL,           offsetof(struct config, enable_pbc)         },
{ "pbc_box",        "15.0 15.0 15.0",   parse_vec,       NULL,           offsetof(struct config, pbc_box)            },
{ "swf_cutoff",     "6.0",              parse_double,    NULL,           offsetof(struct config, swf_cutoff)         },
{ "hess_delta",     "0.001",            parse_double,    double_gt_zero, offsetof(struct config, hess_delta)         },
{ "max_steps",      "100",              parse_int,       int_gt_zero,    offsetof(struct config, max_steps)          },
{ "print_step",     "1",                parse_int,       int_gt_zero,    offsetof(struct config, print_step)         },
{ "temperature",    "300.0",            parse_double,    double_gt_zero, offsetof(struct config, target_temperature) },
{ "time_step",      "1.0",              parse_double,    double_gt_zero, offsetof(struct config, time_step)          },
{ "ensemble",       "nve",              parse_ensemble,  NULL,           offsetof(struct config, ensemble_type)      },
{ "thermostat_tau", "1.0e3",            parse_double,    double_gt_zero, offsetof(struct config, thermostat_tau)     },
{ "opt_tol",        "1.0e-4",           parse_double,    double_gt_zero, offsetof(struct config, opt_tol)            },
{ "fraglib_path",   EFP_DATA_DIR,       parse_string,    NULL,           offsetof(struct config, fraglib_path)       },
{ "userlib_path",   ".",                parse_string,    NULL,           offsetof(struct config, userlib_path)       }
