#!/bin/sh
# FILENAME:  mc_c_testing

#PBS -V
#PBS -q lslipche 
#PBS -l nodes=1:ppn=16
#PBS -l naccesspolicy=shared
#PBS -l walltime=04:00:00
#PBS -N mc_c_testing

cd $PBS_O_WORKDIR

../efpmd/src/efpmd mc_10.in > mc_10.out
../efpmd/src/efpmd mc_11.in > mc_11.out
