#!/bin/sh
# FILENAME:  mc_c_testing

#PBS -V
#PBS -q lslipche 
#PBS -l nodes=1:ppn=16
#PBS -l walltime=10:00:00
#PBS -N s22_test

cd $PBS_O_WORKDIR
for i in *.inp; do ../../../efpmd/src/efpmd $i > $i.out; done
