LIB = common
WARNINGS_SET = HIGH
MKPROFILE = no
MKPICLIB = no

DEBUG_FLAGS ?= -O0 -g
CFLAGS += ${DEBUG_FLAGS}

SRCS = cblas.h \
       compat.c \
       compat.h \
       math_util.h \
       phys_const.h \
       util.c \
       util.h

.include <lib.mk>
