LIB=		efp
INCS=		efp.h
WARNS=		6
NO_MAN=		yes

VERSION!=	cat ${.CURDIR}/../VERSION

USER_CFLAGS?=	-fopenmp
CFLAGS+=	${USER_CFLAGS}

DEBUG_FLAGS?=	-O0 -g

CFLAGS+=	-I${.CURDIR}/../common \
		-DPACKAGE_VERSION="\"${VERSION}\""

SRCS=		disp.c \
		efp.c \
		elec.c \
		elec_grad.c \
		int.c \
		parse.c \
		pol.c \
		xr.c

.include <bsd.lib.mk>
