LIBEFP_MAJOR?=	0
LIBEFP_MINOR?=	0

LIB=		efp
INCS=		efp.h
WARNS=		6
NO_MAN=		yes

USER_CFLAGS?=	-fopenmp
CFLAGS+=	${USER_CFLAGS}

DEBUG_FLAGS?=	-O0 -g

CFLAGS+=	-I${.CURDIR}/../common \
		-DLIBEFP_VERSION="\"${LIBEFP_MAJOR}.${LIBEFP_MINOR}\""

SRCS=		disp.c \
		efp.c \
		elec.c \
		elec_grad.c \
		int.c \
		parse.c \
		pol.c \
		xr.c

.include <bsd.lib.mk>
